name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: | 
          echo "${{ secrets.EC2_SECRET }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: | 
          docker buildx build --platform linux/amd64 -t shhmon/portfolio:latest --push .

      - name: Deploy services
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} "
          cd /home/ec2-user/portfolio &&
          echo 'NODE_ENV=production' > .env &&
          echo 'NEXT_PUBLIC_API_BASE_URL=/noto-backend/api' >> .env &&
          echo 'TEST_GUILD_ID=1306969550851407912' >> .env &&
          echo 'NEXT_PUBLIC_CONTACT_API=${{ secrets.NEXT_PUBLIC_CONTACT_API }}' >> .env &&
          echo 'DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}' >> .env &&
          echo 'CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}' >> .env &&
          echo 'CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}' >> .env &&
          echo 'CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}' >> .env &&
          echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' >> .env &&
          echo 'DB_USER=${{ secrets.DB_USER }}' >> .env &&
          echo 'DB_HOST=${{ secrets.DB_HOST }}' >> .env &&
          echo 'DB_NAME=${{ secrets.DB_NAME }}' >> .env &&
          echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> .env &&
          echo 'DB_PORT=${{ secrets.DB_PORT }}' >> .env &&
          echo 'NOTO_DB_USER=${{ secrets.DB_USER }}' >> .env &&
          echo 'NOTO_DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> .env &&
          echo 'NOTO_DB_HOST=${{ secrets.NOTO_DB_HOST }}' >> .env &&
          echo 'NOTO_DB_NAME=${{ secrets.NOTO_DB_NAME }}' >> .env &&
          echo 'NOTO_DB_PORT=${{ secrets.DB_PORT }}' >> .env &&
          echo 'REACT_APP_WEATHER_API_KEY=${{ secrets.REACT_APP_WEATHER_API_KEY }}' >> .env &&
          docker-compose down &&
          docker system prune -af &&
          docker-compose pull &&
          docker-compose up -d" 